import { PortfolioContent } from "./types";
import { links, certifications, blogPosts } from "./shared";

export const en: PortfolioContent = {
  meta: {
    title: "Riadh MNASRI - Senior Tech Lead & Architect | Cloud Native · AI · Java · Paris",
    description:
      "Freelance Senior Tech Lead & Architect based in Paris. 20+ years of Java/Kotlin experience, Cloud Native (AWS, Azure, GCP), AI Integration. Executive MBA from École Polytechnique. Certified in Java, Spring, Kotlin. Available for engagements.",
    keywords: [
      "riadh mnasri",
      "senior tech lead paris",
      "freelance software architect",
      "lead developer java kotlin",
      "cloud native aws azure gcp",
      "executive master polytechnique",
      "spring certified developer",
      "microservices architect paris",
      "ai integration java",
      "freelance tech lead paris",
      "counterparty risk",
      "capital markets java",
      "tech lead société générale",
    ],
    ogTitle: "Riadh MNASRI - Senior Tech Lead & Architect | AI · Cloud Native · Java",
    ogDescription:
      "20+ years Java/Kotlin · Cloud Native AWS/Azure/GCP · Executive MBA Polytechnique · Certified Kotlin, Spring, Java. Freelance, Paris, €780/day.",
    twitterTitle: "Riadh MNASRI - Senior Tech Lead & Architect",
    twitterDescription: "20+ years Java/Kotlin · Cloud Native · AI · Polytechnique · Freelance, Paris",
    personJobTitle: "Senior Tech Lead & Architect",
    personDescription:
      "Freelance Senior Tech Lead & Architect specialized in Java/Kotlin, Cloud Native, AI Integration. 20+ years of experience. Executive MBA from École Polytechnique.",
  },

  nav: {
    links: [
      { href: "#about", label: "About" },
      { href: "#ai", label: "AI & Innovation" },
      { href: "#skills", label: "Skills" },
      { href: "#experience", label: "Experience" },
      { href: "#education", label: "Education" },
      { href: "#projects", label: "Projects" },
      { href: "#services", label: "Services" },
      { href: "#contact", label: "Contact" },
    ],
    cta: "Contact me",
  },

  floatingCta: "Contact me",

  hero: {
    availability: "Available for freelance engagements",
    name: "Riadh MNASRI",
    title: "Senior Tech Lead & Architect",
    subtitle: "AI-Driven Solutions · Cloud Native · Java & Kotlin Expert",
    tagline: "20 years of engineering. Cloud-native architectures that transform.\nAI in the service of your business.",
    badges: [
      "Anthropic Certified",
      "Java Certified",
      "Kotlin Certified",
      "Spring Certified",
      "Executive Master @ Polytechnique",
      "Paris · Freelance · €780/day",
    ],
    ctaContact: "Contact me",
    ctaProjects: "View my projects",
    maltLabel: "Malt · €780/day",
    location: "Paris · Hybrid · Remote",
    scroll: "Scroll",
    photoAlt: "Riadh MNASRI - Senior Tech Lead & Architect",
    polytechniqueBadge: "Polytechnique",
    stats: [
      { value: 20, suffix: "+", label: "years of experience" },
      { value: 7735, suffix: "", label: "LinkedIn followers" },
      { value: 780, suffix: "€", label: "day rate" },
      { value: 19, suffix: "", label: "certifications" },
    ],
  },

  clientLogos: {
    label: "Trusted by",
  },

  about: {
    label: "About",
    titlePrefix: "The person behind ",
    titleHighlight: "the code",
    bio: [
      "I help organizations turn technical debt into scalable, high-performance assets. Cloud-native migration (AWS, Azure, GCP), AI integration, hardened microservices architectures: I make sure technology drives growth instead of holding it back.",
      "20 years of engineering excellence combined with a strategic outlook (Executive Master @ École Polytechnique). Certified in Kotlin, Java and Spring, and an early adopter of AI integration (GitHub Copilot, Claude) into development workflows.",
      "Currently Tech Lead & Architect @ Cartan Trade, working on AI initiatives and the credit insurance risk platform. Available for freelance engagements in Paris and remote.",
    ],
    tags: ["Craftsman", "Speaker", "Mentor", "Open-source", "AI Pioneer"],
    timeline: [
      { year: "2026", event: "AI Tech Lead & Architect @ Cartan Trade" },
      { year: "2026", event: "Claude Code 101 & Subagents - Anthropic Certified" },
      { year: "2024", event: "Executive MBA - Digital Transformation Strategist, École Polytechnique" },
      { year: "2024", event: "Tech Lead Java Spark Azure AI @ Société Générale CIB" },
      { year: "2022", event: "Tech Lead Fullstack Java Angular AWS @ GRTgaz" },
      { year: "2021", event: "Lead Backend Java Kotlin GCP @ Groupe Casino" },
      { year: "2020", event: "Tech Lead Full Stack @ Ministère de la Justice" },
      { year: "2020", event: "Kotlin Certified Developer - JetBrains" },
      { year: "2017", event: "CEO WeHighTech · Spring Certified Professional" },
      { year: "2007", event: "Sun Certified Java Programmer - Oracle" },
      { year: "2004", event: "Computer Engineering Degree" },
    ],
  },

  aiSection: {
    badge: "AI & Innovation",
    titlePrefix: "AI, not just a ",
    titleHighlight: "buzzword",
    subtitle: "Anthropic-certified, field-tested. I integrate AI into your projects in a structured, secure and immediately profitable way.",
    impacts: [
      { value: "~+30%", label: "development velocity", detail: "via GitHub Copilot & Claude @ SGCIB" },
      { value: "Day 1", label: "operational integration", detail: "AI in your pipelines from day one" },
      { value: "2026", label: "dual Anthropic certified", detail: "Claude Code 101 · Introduction to Subagents" },
    ],
    toolsLabel: "Tools I work with",
    certifiedLabel: "Certified",
    journeyLabel: "My AI journey",
    timeline: [
      { year: "2026", event: "Certified Claude Code 101 - Anthropic", color: "#D4AF37" },
      { year: "2026", event: "Certified Introduction to Subagents - Anthropic", color: "#D4AF37" },
      { year: "2025", event: "Claude Code training @ SFEIR Institute", color: "#D4AF37" },
      { year: "2024", event: "Pioneered GitHub Copilot in production @ SGCIB", color: "#D4AF37" },
      { year: "2024", event: "Agent-ready architecture on enterprise Java systems", color: "#D4AF37" },
      { year: "2023", event: "Active LLM watch: AI-driven architecture, security, agents", color: "#94A3B8" },
    ],
    thoughtLeadershipLabel: "Thought Leadership",
    thoughtLeadershipTitle: "I share my thoughts on AI every week",
    followLinkedIn: "Follow on LinkedIn",
    reactionsLabel: "reactions",
  },

  whyMe: {
    label: "Why me",
    titlePrefix: "What sets me ",
    titleHighlight: "apart",
    subtitle: "Three concrete reasons to choose Riadh MNASRI for your next technical challenge.",
    differentiators: [
      {
        icon: "graduation",
        color: "#D4AF37",
        gradient: "linear-gradient(135deg, rgba(212,175,55,0.12), rgba(212,175,55,0.04))",
        border: "rgba(212,175,55,0.25)",
        tag: "Strategic Vision",
        title: "The bridge between the C-suite and engineering",
        body: "Executive MBA from École Polytechnique + 20 years in the field. I translate your business challenges into technical architectures, and your technical constraints into strategic decisions. I speak the language of your CTO as fluently as your dev team's.",
        kpis: ["Executive MBA Polytechnique", "20+ years of experience", "C-level ↔ Engineering leadership"],
      },
      {
        icon: "energy",
        color: "#D4AF37",
        gradient: "linear-gradient(135deg, rgba(212,175,55,0.12), rgba(212,175,55,0.04))",
        border: "rgba(212,175,55,0.25)",
        tag: "Proven Performance",
        title: "Measurable results, not promises",
        body: "At Société Générale CIB, I helped significantly cut processing times on a critical risk engine and accelerate dev velocity through AI integration. Real, detailed figures below — not empty promises.",
        kpis: ["Up to −50% processing time @ SGCIB", "~+30% dev velocity with AI", "99%+ target availability"],
      },
      {
        icon: "ai",
        color: "#D4AF37",
        gradient: "linear-gradient(135deg, rgba(212,175,55,0.1), rgba(212,175,55,0.03))",
        border: "rgba(212,175,55,0.25)",
        tag: "AI-Ready from Day 1",
        title: "AI in your pipelines, starting now",
        body: "Anthropic certified (Claude Code, Subagents), an early adopter of GitHub Copilot & Claude in enterprise settings. I integrate AI into your development workflows in a secure, controlled and immediately actionable way.",
        kpis: ["Claude Code 101 - Anthropic 2026", "GitHub Copilot in production", "Agent-ready architecture"],
      },
    ],
    ctaTitle: "Ready to transform your stack?",
    ctaSubtitle: "Available for freelance engagements · Paris & Remote · €780/day",
    ctaButton: "Let's talk about your project →",
  },

  skills: {
    label: "Skills",
    titlePrefix: "Technical ",
    titleHighlight: "& Domain",
    subtitle: "20 years in the field, across demanding sectors. A rare double expertise: cloud-native architecture combined with a deep understanding of business domains.",
    categories: [
      {
        icon: "architecture",
        category: "Architecture",
        items: ["Microservices", "DDD", "Hexagonal", "Event-Driven", "CQRS", "Cloud-Native"],
      },
      {
        icon: "jvm",
        category: "JVM & Languages",
        items: ["Java 21+", "Kotlin", "Scala", "TypeScript", "Spring Boot", "Reactor"],
      },
      {
        icon: "cloud",
        category: "Cloud & Infra",
        items: ["AWS", "Azure", "GCP", "Kubernetes", "Docker", "Terraform"],
      },
      {
        icon: "ai",
        category: "AI & Innovation",
        items: ["GitHub Copilot", "Claude / Anthropic", "AI Agents", "LLM Integration", "Cybersecurity", "OWASP"],
      },
      {
        icon: "data",
        category: "Data & Messaging",
        items: ["Apache Kafka", "Apache Spark", "Elasticsearch", "PostgreSQL", "MongoDB", "Axon"],
      },
      {
        icon: "quality",
        category: "Quality & Leadership",
        items: ["TDD", "BDD", "Clean Code", "DevSecOps", "CI/CD", "Mentoring"],
      },
    ],
    domainDividerLabel: "Domain & Sector Expertise",
    domains: [
      {
        icon: "finance",
        sector: "Capital Markets & Risk",
        color: "#D4AF37",
        client: "Société Générale CIB",
        items: [
          "Counterparty risk (CCR / XVA)",
          "Cloud-native risk calculation engines",
          "Financial regulation (FRTB, CRD IV/V)",
          "Capital Markets & CIB",
          "Spark performance optimization (~+50%)",
        ],
      },
      {
        icon: "energy",
        sector: "Energy & Utilities",
        color: "#38BDF8",
        client: "GRTgaz",
        items: [
          "Energy distribution management",
          "National gas transport network",
          "Vitally Important Operators (OIV)",
          "High-availability real-time systems",
          "Critical infrastructure & strict SLAs",
        ],
      },
      {
        icon: "retail",
        sector: "Retail & Large-Scale Distribution",
        color: "#22C55E",
        client: "Groupe Casino",
        items: [
          "Campaign & promotional offer management",
          "Customer loyalty engines",
          "Large-scale product catalog",
          "E-commerce & marketing platforms",
          "Event-driven architecture on GCP",
        ],
      },
      {
        icon: "justice",
        sector: "Public Sector & Justice",
        color: "#64748B",
        client: "Ministère de la Justice",
        items: [
          "Digitization of judicial procedures",
          "Security & GDPR / government compliance",
          "Government system interoperability",
          "Sovereign OpenShift deployment",
          "Digital transformation support",
        ],
      },
      {
        icon: "rocket",
        sector: "Consulting & Digital Transformation",
        color: "#A78BFA",
        client: "WeHighTech (CEO)",
        items: [
          "Technical due diligence & audits",
          "Leading complex multi-team projects",
          "Recruiting and managing senior engineers",
          "Craftsmanship culture & engineering excellence",
          "Supporting large accounts & scale-ups",
        ],
      },
    ],
    moreLabel: "Public, private, international",
    moreDesc: "Able to quickly adapt to any business domain, backed by 20 years of varied engagements.",
  },

  experience: {
    label: "Experience",
    titlePrefix: "20 years in the ",
    titleHighlight: "field",
    subtitle: "Banking, energy, retail, public sector: critical cloud-native systems for the biggest players.",
    stackLabel: "Stack",
    items: [
      {
        company: "Cartan Trade",
        role: "Senior Tech Lead & Architect",
        period: "Aug 2026 – present",
        emoji: "institution",
        highlights: [
          "Integrating advanced AI capabilities (Claude) to reshape risk assessment and automate decision workflows",
          "Translating credit risk business logic into innovative technical solutions, working directly with business teams",
          "Co-building default risk calculation models with the existing tech teams",
          "Scalable full-stack architecture on Google Cloud Platform (GCP), Kotlin development",
        ],
        stack: "Kotlin · Google Cloud Platform · Claude APIs · Risk Modeling",
      },
      {
        company: "Société Générale CIB (SGCIB)",
        role: "Technical Leader Java Spark Azure AI",
        period: "Jan 2024 – Aug 2026",
        emoji: "finance",
        highlights: [
          "Cloud-native architecture on Azure & Kubernetes for a counterparty risk engine",
          "Significant reduction (up to 50%) in processing time via algorithmic optimization and Spark tuning",
          "Notable acceleration (~30%) of the dev cycle through GitHub Copilot and AI tooling adoption",
          "TDD/BDD and Clean Code culture: significant reduction in production bugs",
          "Automated CI/CD (GitHub/Jenkins) in a highly regulated environment",
        ],
        stack: "Java · Spring Boot · Apache Spark · Azure · Kubernetes · Kafka · AI · Jenkins",
      },
      {
        company: "WeHighTech",
        role: "CEO & Founder",
        period: "Jan 2017 – present",
        emoji: "rocket",
        highlights: [
          "Founded and led a tech consulting company focused on quality and excellence",
          "Ran freelance engagements for large accounts (banking, energy, retail, public sector)",
          "Recruited and managed senior engineers",
          "Company culture centered on craftsmanship and innovation",
        ],
        stack: "Kotlin · Angular · Java · Spring Boot · Cloud",
      },
      {
        company: "GRTgaz",
        role: "Technical Leader Fullstack Java Angular AWS Terraform",
        period: "Mar 2022 – Feb 2024",
        emoji: "energy",
        highlights: [
          "Designed and built an energy distribution management platform",
          "Microservices architecture with Axon Framework and reactive programming (Reactor)",
          "CI/CD on AWS with Terraform - Infrastructure as Code",
          "Mentored developers, code review, pair programming, TDD",
        ],
        stack: "Java 17 · Kotlin · Spring Boot · Axon · Reactor · Angular · AWS · Terraform · Kafka",
      },
      {
        company: "Groupe Casino",
        role: "Lead Backend Developer Java Kotlin GCP",
        period: "Jan 2021 – Mar 2022",
        emoji: "retail",
        highlights: [
          "Designed and built a campaign and offer management platform",
          "API design, Kotlin & Java development, SOLID, KISS, DRY practices",
          "CI/CD on Google Cloud Platform (GCP) with Kubernetes",
          "TDD, BDD, functional programming, mentoring",
        ],
        stack: "Java 11 · Kotlin · Spring Boot · GCP · Kubernetes · PostgreSQL · Liquibase",
      },
      {
        company: "Ministère de la Justice",
        role: "Technical Leader Full Stack",
        period: "Jun 2020 – Jan 2021",
        emoji: "justice",
        highlights: [
          "Full-stack technical lead (Java/Kotlin backend + Angular frontend)",
          "Internal brown bag lunches: Functional Programming with Java Streams, Kotlin from Zero to Hero",
          "Craftsmanship: Clean Code, TDD, code review, pair programming",
          "Deployment on OpenShift",
        ],
        stack: "Java 11 · Kotlin · Spring Boot · Angular · Jenkins · Docker · Openshift",
      },
    ],
  },

  education: {
    label: "Education",
    titlePrefix: "Academic ",
    titleHighlight: "excellence",
    subtitle: "An engineering background grounded in technical depth, elevated by high-level strategic thinking.",
    projectLabel: "Transformation project",
    skillsLabel: "Skills developed",
    items: [
      {
        school: "École Polytechnique",
        logo: "graduation",
        degree: "Executive MBA",
        field: "Digital Transformation Strategist",
        promo: "Cohort 7",
        year: "2024",
        highlight: true,
        color: "#D4AF37",
        project: "Transforming a cybersecurity products distributor into a managed services provider.",
        skills: [
          "Design and drive digital transformation strategy",
          "Create value from cutting-edge technologies",
          "Build business models based on technological innovation",
          "Spark and steer collective transformation dynamics",
          "Support teams through organizational change",
        ],
        url: "https://www.polytechnique.edu/executive-education",
      },
      {
        school: "École Polytechnique",
        logo: "graduation",
        degree: "Certification",
        field: "Digital Business - Act on the Digital World",
        promo: "",
        year: "2023",
        highlight: false,
        color: "#D4AF37",
        project: "",
        skills: [],
        url: "https://www.polytechnique.edu/executive-education",
      },
      {
        school: "EMI - École Mohammadia d'Ingénieurs",
        logo: "gear",
        degree: "Engineering Degree",
        field: "Computer Science Engineering",
        promo: "",
        year: "2004",
        highlight: false,
        color: "#D4AF37",
        project: "",
        skills: [],
        url: "",
      },
    ],
  },

  projects: {
    label: "Projects & Contributions",
    titlePrefix: "Proof, ",
    titleHighlight: "not just words",
    subtitle: "Open-source code, talks, articles and thoughts on AI, architecture and tech leadership.",
    linkedinInsightsTitle: "LinkedIn Insights",
    followersLabel: "7,735 followers",
    reactionsLabel: "reactions",
    githubTitle: "GitHub Open Source",
    reposLabel: "153 repos",
    talksTitle: "Talks & Presentations",
    slideshareLabel: "SlideShare",
    blogTitle: "Blog Posts",
    blogLabel: "riadhmnasri.fr",
    items: [
      {
        title: "kotlin-counterparty-risk",
        desc: "Kotlin/JVM OSS library: exposure, expected loss and CVA on repos and securities lending",
        tags: ["Kotlin", "Finance", "Risk"],
        url: "https://github.com/riadh-mnasri/kotlin-counterparty-risk",
      },
      {
        title: "kotlin-chess-tournament",
        desc: "Kotlin/JVM OSS library: Swiss pairing, Elo rating calculation and tournament standings",
        tags: ["Kotlin", "OSS", "Algorithms"],
        url: "https://github.com/riadh-mnasri/kotlin-chess-tournament",
      },
      {
        title: "missionmatch",
        desc: "Reference app for DDD, Hexagonal, TDD/BDD and Kafka - Kotlin/Spring Boot + Angular, Terraform/AWS",
        tags: ["Kotlin", "DDD", "Kafka"],
        url: "https://github.com/riadh-mnasri/missionmatch",
      },
      {
        title: "hexray",
        desc: "Hexagonal/DDD architecture audit CLI (TypeScript + Kotlin), reports generated by an AI agent",
        tags: ["CLI", "Architecture", "AI"],
        url: "https://github.com/riadh-mnasri/hexray",
      },
    ],
    talks: [
      { title: "Architectures Microservices", views: "871 views", icon: "architecture" },
      { title: "Git l'essentiel", views: "1,200 views", icon: "github" },
      { title: "Discover Micronaut", views: "306 views", icon: "rocket" },
      { title: "Kotlin ArrowKt", views: "318 views", icon: "target" },
      { title: "BBL Reactive Programming", views: "197 views", icon: "energy" },
      { title: "Functional Programming with Kotlin", views: "122 views", icon: "λ" },
    ],
    linkedinPosts: [
      {
        title: "AI as a thinking partner, not a code generator",
        excerpt: "After more than 20 years of development, I didn't expect an AI assistant to still change how I think about writing code. The quality of the answers depends far more on the questions I ask than on the model I use.",
        tags: ["AI", "Craftsmanship", "Reflection"],
        reactions: 25,
      },
      {
        title: "Documentation that updates itself",
        excerpt: "Living Documentation: I tried it, and it's a game-changer for a team. We all know that situation where a new developer runs into outdated docs...",
        tags: ["Claude Code", "Documentation", "Augmented Dev"],
        reactions: 12,
      },
      {
        title: "Claude Code training @ SFEIR Institute",
        excerpt: "The developer job is evolving fast, and the shift toward the augmented-developer paradigm is now a reality. I just wrapped up Claude Code training at SFEIR Institute.",
        tags: ["Claude Code", "Anthropic", "Augmented Dev"],
        reactions: 23,
      },
    ],
    blogPosts,
  },

  certifications: {
    label: "Certifications & Community",
    titlePrefix: "19 certifications, ",
    titleHighlight: "proven expertise",
    subtitle: "Recognized certifications across the most strategic domains: AI, Cloud, Architecture, JVM.",
    aiBadge: "AI & Anthropic - 2026",
    allLabel: "All certifications",
    communityTitlePrefix: "Community ",
    communityTitleHighlight: "involvement",
    items: certifications,
    community: [
      { icon: "graduation", name: "École Polytechnique", desc: "Executive Master - Cohort 7, Digital Strategist" },
      { icon: "ai", name: "Anthropic Certified", desc: "Claude Code 101 · Introduction to Subagents" },
      { icon: "jvm", name: "JUG Paris", desc: "Java User Group - Active member" },
      { icon: "sandwich", name: "Brown Bag Lunch", desc: "Speaker & trainer (Kotlin, Java, FP...)" },
      { icon: "github", name: "GitHub", desc: "153 repos · Arctic Code Vault Contributor" },
      { icon: "pen", name: "Technical Blog", desc: "riadhmnasri.fr - Architecture, AI, Finance & Risk" },
      { icon: "linkedin", name: "LinkedIn", desc: "7,735 followers · AI & Architecture watch" },
      { icon: "chess", name: "Chess Club CEBC", desc: "Bois-Colombes - Coaching young players" },
    ],
  },

  testimonials: {
    label: "Testimonials",
    titlePrefix: "What ",
    titleHighlight: "clients say",
    subtitle: "Concrete results, satisfied teams. A few words from colleagues and clients.",
    items: [
      {
        quote: "I worked with Riadh as a developer on the team he was leading. He's the kind of profile any company would want when looking for someone with strong problem-solving ability and a knack for reducing time-to-market. He's talented and always ready to help others thanks to his deep technical knowledge. It was a real pleasure working with him.",
        author: "Abdelaziz Houmadi",
        company: "Senior Full Stack Java & AWS",
        emoji: "developer",
        color: "#D4AF37",
      },
      {
        quote: "I had the chance to work with Riadh, a very professional colleague. He has a genuine sense of commitment to delivering his projects on time for his clients' benefit. His technical expertise in service-oriented architectures, his ability to grow every member of his squad both technically and personally, and how easily he interacts with the teams around him make him a major asset on any project.",
        author: "Mounir Bayach",
        company: "Business Engineer (former direct manager)",
        emoji: "compass",
        color: "#22C55E",
      },
      {
        quote: "I had the privilege of working on the same team as Riadh. He's a passionate, hard-working developer with strong skills who genuinely enjoys sharing knowledge. His team spirit, professionalism and pursuit of excellence are qualities I really valued in him.",
        author: "Van-Minh Pho",
        company: "Developer / Technical Lead Java & Kotlin",
        emoji: "handshake",
        color: "#A78BFA",
      },
      {
        quote: "It was a pleasure working with Riadh. He's a solid and passionate Java and Kotlin developer for whom quality and doing things right really matter. He's also an excellent speaker who shares his knowledge at tech events (Brown Bag Lunch). If you're looking for a strong senior developer, I highly recommend him.",
        author: "Romain Schlick",
        company: "Technical Leader & Senior Developer",
        emoji: "mic",
        color: "#38BDF8",
      },
    ],
    footerPrefix: "Real recommendations, published on my ",
    footerLinkLabel: "LinkedIn profile",
  },

  services: {
    label: "Services",
    titlePrefix: "What I can do ",
    titleHighlight: "for you",
    subtitle: "Available for freelance engagements in Paris and remote. Day rate: €780/day.",
    items: [
      {
        icon: "☁️",
        title: "Cloud-Native Migration & Architecture",
        desc: "Migrating legacy systems to the Cloud (AWS, Azure, GCP). Designing scalable microservices architectures targeting 99%+ availability. Kubernetes, Terraform, Kafka.",
        target: "CIOs, CTOs, large accounts & scale-ups",
      },
      {
        icon: "🤖",
        title: "AI Integration & Modernization",
        desc: "Integrating AI into your development pipelines (Copilot, Claude, LLMs). Hardening architectures (OWASP, OAuth2/OIDC). Accelerating time-to-market.",
        target: "Tech teams looking to adopt AI",
      },
      {
        icon: "🧭",
        title: "Technical Leadership & Mentoring",
        desc: "Technical leadership of engineering teams, craftsmanship culture (TDD, Clean Code, DDD), DevSecOps. I bridge C-level strategy and engineering reality on the ground.",
        target: "Startups, mid-size and large companies",
      },
    ],
    dayRateBig: "€780 / day",
    dayRateSubtitle: "Average day rate · Paris & Remote · Available now",
    ctaButton: "Let's talk about your project",
  },

  contact: {
    label: "Contact",
    titlePrefix: "Let's talk about your ",
    titleHighlight: "project",
    subtitle: "An engagement, training, or a technical audit? I reply within 24 hours.",
    sentTitle: "Message sent!",
    sentDesc: "I'll get back to you within 24 hours.",
    namePlaceholder: "First / Last name *",
    emailPlaceholder: "Email *",
    companyPlaceholder: "Company (optional)",
    typePlaceholder: "Type of engagement",
    typeOptions: ["Technical architecture", "Lead Developer / Tech Lead", "Training / Brown Bag Lunch", "Other"],
    messagePlaceholder: "Describe what you need... *",
    errorMessage: "Something went wrong. Please email me directly instead.",
    sendingLabel: "Sending...",
    sendLabel: "Send message",
    emailLabel: "Email",
    locationLabel: "Location",
    locationValue: "Paris, France · Remote OK",
    maltLabel: "Malt",
    maltCta: "View my Malt profile",
    findMeLabel: "Find me on",
    githubLabel: "GitHub",
    linkedinLabel: "LinkedIn",
    blogLabel: "Blog",
    availableLabel: "Available for engagements",
    dayRate: "€780 / day",
  },

  footer: {
    role: "Senior Software Architect & Lead Developer",
    lastUpdatedLabel: "Last updated",
  },

  chat: {
    toggleOpen: "Ask a question",
    toggleClose: "Close",
    title: "Profile assistant",
    subtitle: "Questions about Riadh MNASRI",
    emptyPrompt: "Ask a question about Riadh's skills, experience or availability.",
    suggestions: [
      "What are his AI skills?",
      "Is he available for an engagement?",
      "What's his experience in capital markets?",
    ],
    inputPlaceholder: "Your question...",
    errorMessage: "Something went wrong. Try again or email riadh.mnasri@gmail.com directly.",
  },

  links,
};
