import { PortfolioContent } from "./types";
import { links, certifications, blogPosts } from "./shared";

export const fr: PortfolioContent = {
  meta: {
    title: "Riadh MNASRI - Senior Tech Lead & Architect | Cloud Native · AI · Java · Paris",
    description:
      "Senior Tech Lead & Architect freelance à Paris. 20+ ans d'expérience Java/Kotlin, Cloud Native (AWS, Azure, GCP), AI Integration. Executive MBA École Polytechnique. Certifié Java, Spring, Kotlin. Disponible pour missions.",
    keywords: [
      "riadh mnasri",
      "senior tech lead paris",
      "architecte logiciel freelance",
      "lead developer java kotlin",
      "cloud native aws azure gcp",
      "executive master polytechnique",
      "spring certified developer",
      "microservices architect paris",
      "ai integration java",
      "freelance tech lead paris",
      "risque de contrepartie",
      "finance de marche java",
      "tech lead société générale",
    ],
    ogTitle: "Riadh MNASRI - Senior Tech Lead & Architect | AI · Cloud Native · Java",
    ogDescription:
      "20+ ans Java/Kotlin · Cloud Native AWS/Azure/GCP · Executive MBA Polytechnique · Certifié Kotlin, Spring, Java. Freelance Paris 780€/j.",
    twitterTitle: "Riadh MNASRI - Senior Tech Lead & Architect",
    twitterDescription: "20+ ans Java/Kotlin · Cloud Native · AI · Polytechnique · Freelance Paris",
    personJobTitle: "Senior Tech Lead & Architect",
    personDescription:
      "Senior Tech Lead & Architect freelance spécialisé Java/Kotlin, Cloud Native, AI Integration. 20+ ans d'expérience. Executive MBA École Polytechnique.",
  },

  nav: {
    links: [
      { href: "#about", label: "À propos" },
      { href: "#ai", label: "IA & Innovation" },
      { href: "#skills", label: "Skills" },
      { href: "#experience", label: "Expérience" },
      { href: "#education", label: "Formation" },
      { href: "#projects", label: "Projets" },
      { href: "#services", label: "Services" },
      { href: "#contact", label: "Contact" },
    ],
    cta: "Me contacter",
  },

  floatingCta: "Me contacter",

  hero: {
    availability: "Disponible pour missions freelance",
    name: "Riadh MNASRI",
    title: "Senior Tech Lead & Architect",
    subtitle: "AI-Driven Solutions · Cloud Native · Java & Kotlin Expert",
    tagline: "20 ans d'ingénierie. Des architectures cloud-native qui transforment.\nL'IA au service de votre business.",
    badges: [
      "Anthropic Certified",
      "Java Certifié",
      "Kotlin Certifié",
      "Spring Certifié",
      "Executive Master @ Polytechnique",
      "Paris · Freelance · 780€/j",
    ],
    ctaContact: "Me contacter",
    ctaProjects: "Voir mes projets",
    maltLabel: "Malt · 780€/j",
    location: "Paris · Hybride · Remote",
    scroll: "Scroll",
    photoAlt: "Riadh MNASRI - Senior Tech Lead & Architect",
    polytechniqueBadge: "Polytechnique",
    stats: [
      { value: 20, suffix: "+", label: "ans d'expérience" },
      { value: 7735, suffix: "", label: "abonnés LinkedIn" },
      { value: 780, suffix: "€", label: "TJM journalier" },
      { value: 19, suffix: "", label: "certifications" },
    ],
  },

  clientLogos: {
    label: "Ils m'ont fait confiance",
  },

  about: {
    label: "À propos",
    titlePrefix: "L'humain derrière ",
    titleHighlight: "le code",
    bio: [
      "J'aide les organisations à transformer leur dette technique en actifs scalables et haute performance. Migration Cloud-Native (AWS, Azure, GCP), intégration de l'IA, sécurisation des architectures Microservices : j'assure que la technologie propulse la croissance plutôt que de la freiner.",
      "20 ans d'excellence ingénierie combinés à une vision stratégique (Executive Master @ École Polytechnique). Certifié Kotlin, Java et Spring, pionnier de l'intégration de l'IA (GitHub Copilot, Claude) dans les workflows de développement.",
      "Actuellement Tech Lead & Architect @ Cartan Trade, sur les initiatives IA et la plateforme de risque de crédit assurance. Disponible pour missions freelance à Paris et en remote.",
    ],
    tags: ["Artisan du code", "Speaker", "Mentor", "Open-source", "AI Pioneer"],
    timeline: [
      { year: "2026", event: "Tech Lead & Architect IA @ Cartan Trade" },
      { year: "2026", event: "Claude Code 101 & Subagents - Anthropic Certified" },
      { year: "2024", event: "Executive MBA - Stratège de la Transformation Numérique, École Polytechnique" },
      { year: "2024", event: "Tech Lead Java Spark Azure AI @ Société Générale CIB" },
      { year: "2022", event: "Tech Lead Fullstack Java Angular AWS @ GRTgaz" },
      { year: "2021", event: "Lead Backend Java Kotlin GCP @ Groupe Casino" },
      { year: "2020", event: "Tech Lead Full Stack @ Ministère de la Justice" },
      { year: "2020", event: "Kotlin Certified Developer - JetBrains" },
      { year: "2017", event: "CEO WeHighTech · Spring Certified Professional" },
      { year: "2007", event: "Sun Certified Java Programmer - Oracle" },
      { year: "2004", event: "Diplôme Ingénieur Informatique" },
    ],
  },

  aiSection: {
    badge: "AI & Innovation",
    titlePrefix: "L'IA, pas comme un ",
    titleHighlight: "buzzword",
    subtitle: "Certifié Anthropic, formé sur le terrain. J'intègre l'IA de façon structurée, sécurisée et immédiatement rentable dans vos projets.",
    impacts: [
      { value: "~+30%", label: "vélocité de développement", detail: "via GitHub Copilot & Claude @ SGCIB" },
      { value: "J+1", label: "intégration opérationnelle", detail: "IA dans vos pipelines dès le premier jour" },
      { value: "2026", label: "double certifié Anthropic", detail: "Claude Code 101 · Introduction to Subagents" },
    ],
    toolsLabel: "Outils maîtrisés",
    certifiedLabel: "Certifié",
    journeyLabel: "Mon parcours IA",
    timeline: [
      { year: "2026", event: "Certifié Claude Code 101 - Anthropic", color: "#D4AF37" },
      { year: "2026", event: "Certifié Introduction to Subagents - Anthropic", color: "#D4AF37" },
      { year: "2025", event: "Formation Claude Code @ SFEIR Institute", color: "#D4AF37" },
      { year: "2024", event: "Pionnier GitHub Copilot en production @ SGCIB", color: "#D4AF37" },
      { year: "2024", event: "Architecture Agent-Ready sur systèmes Java enterprise", color: "#D4AF37" },
      { year: "2023", event: "Veille active LLM : architecture AI-Driven, sécurité, agents", color: "#94A3B8" },
    ],
    thoughtLeadershipLabel: "Thought Leadership",
    thoughtLeadershipTitle: "Je partage mes réflexions sur l'IA chaque semaine",
    followLinkedIn: "Suivre sur LinkedIn",
    reactionsLabel: "réactions",
  },

  whyMe: {
    label: "Pourquoi moi",
    titlePrefix: "Ce qui me ",
    titleHighlight: "différencie",
    subtitle: "Trois raisons concrètes de choisir Riadh MNASRI pour votre prochain défi technique.",
    differentiators: [
      {
        icon: "graduation",
        color: "#D4AF37",
        gradient: "linear-gradient(135deg, rgba(212,175,55,0.12), rgba(212,175,55,0.04))",
        border: "rgba(212,175,55,0.25)",
        tag: "Vision Stratégique",
        title: "Le pont entre la C-suite et l'ingénierie",
        body: "Executive MBA à l'École Polytechnique + 20 ans sur le terrain. Je traduis vos enjeux business en architectures techniques et vos contraintes techniques en décisions stratégiques. Je parle autant à votre DSI qu'à votre équipe dev.",
        kpis: ["Executive MBA Polytechnique", "20+ ans d'expérience", "Leadership C-level ↔ Engineering"],
      },
      {
        icon: "energy",
        color: "#D4AF37",
        gradient: "linear-gradient(135deg, rgba(212,175,55,0.12), rgba(212,175,55,0.04))",
        border: "rgba(212,175,55,0.25)",
        tag: "Performance Prouvée",
        title: "Des résultats mesurables, pas des promesses",
        body: "Chez Société Générale CIB, j'ai contribué à réduire nettement les temps de traitement sur un moteur de risque critique, et à accélérer la vélocité dev via l'intégration de l'IA. Des ordres de grandeur, détaillés ci-dessous, pas des promesses en l'air.",
        kpis: ["Jusqu'à −50% temps de traitement @ SGCIB", "~+30% vélocité dev avec l'IA", "99%+ disponibilité visée"],
      },
      {
        icon: "ai",
        color: "#D4AF37",
        gradient: "linear-gradient(135deg, rgba(212,175,55,0.1), rgba(212,175,55,0.03))",
        border: "rgba(212,175,55,0.25)",
        tag: "AI-Ready dès J+1",
        title: "L'IA dans vos pipelines, maintenant",
        body: "Certifié Anthropic (Claude Code, Subagents), pionnier de l'intégration GitHub Copilot & Claude en contexte enterprise. J'intègre l'IA dans vos workflows de développement de façon sécurisée, maîtrisée et immédiatement actionnable.",
        kpis: ["Claude Code 101 - Anthropic 2026", "GitHub Copilot en production", "Architecture Agent-Ready"],
      },
    ],
    ctaTitle: "Prêt à transformer votre stack ?",
    ctaSubtitle: "Disponible pour missions freelance · Paris & Remote · 780€/j",
    ctaButton: "Discutons de votre projet →",
  },

  skills: {
    label: "Compétences",
    titlePrefix: "Technique ",
    titleHighlight: "& Métier",
    subtitle: "20 ans sur le terrain, dans des secteurs exigeants. Une double expertise rare : architecture cloud-native et compréhension profonde des domaines fonctionnels.",
    categories: [
      {
        icon: "architecture",
        category: "Architecture",
        items: ["Microservices", "DDD", "Hexagonal", "Event-Driven", "CQRS", "Cloud-Native"],
      },
      {
        icon: "jvm",
        category: "JVM & Langages",
        items: ["Java 21+", "Kotlin", "Scala", "TypeScript", "Spring Boot", "Reactor"],
      },
      {
        icon: "cloud",
        category: "Cloud & Infra",
        items: ["AWS", "Azure", "GCP", "Kubernetes", "Docker", "Terraform"],
      },
      {
        icon: "ai",
        category: "AI & Innovation",
        items: ["GitHub Copilot", "Claude / Anthropic", "AI Agents", "LLM Integration", "Cybersécurité", "OWASP"],
      },
      {
        icon: "data",
        category: "Data & Messaging",
        items: ["Apache Kafka", "Apache Spark", "Elasticsearch", "PostgreSQL", "MongoDB", "Axon"],
      },
      {
        icon: "quality",
        category: "Qualité & Leadership",
        items: ["TDD", "BDD", "Clean Code", "DevSecOps", "CI/CD", "Mentoring"],
      },
    ],
    domainDividerLabel: "Expertise Métier & Sectorielle",
    domains: [
      {
        icon: "finance",
        sector: "Finance de Marché & Risque",
        color: "#D4AF37",
        client: "Société Générale CIB",
        items: [
          "Risque de contrepartie (CCR / XVA)",
          "Moteurs de calcul de risque cloud-native",
          "Régulation financière (FRTB, CRD IV/V)",
          "Capital Markets & CIB",
          "Optimisation de performance Spark (~+50%)",
        ],
      },
      {
        icon: "energy",
        sector: "Énergie & Utilities",
        color: "#38BDF8",
        client: "GRTgaz",
        items: [
          "Gestion de la distribution énergétique",
          "Réseau de transport de gaz national",
          "Opérateurs d'Importance Vitale (OIV)",
          "Systèmes temps réel haute disponibilité",
          "Infrastructure critique & SLA stricts",
        ],
      },
      {
        icon: "retail",
        sector: "Retail & Grande Distribution",
        color: "#22C55E",
        client: "Groupe Casino",
        items: [
          "Gestion de campagnes & offres promotionnelles",
          "Moteurs de fidélisation client",
          "Catalogue produit à grande échelle",
          "Plateformes e-commerce & marketing",
          "Architecture événementielle GCP",
        ],
      },
      {
        icon: "justice",
        sector: "Secteur Public & Justice",
        color: "#64748B",
        client: "Ministère de la Justice",
        items: [
          "Dématérialisation de procédures judiciaires",
          "Sécurité & conformité RGPD / État",
          "Interopérabilité des systèmes d'État",
          "Déploiement Openshift souverain",
          "Accompagnement transformation numérique",
        ],
      },
      {
        icon: "rocket",
        sector: "Conseil & Transformation Digitale",
        color: "#A78BFA",
        client: "WeHighTech (CEO)",
        items: [
          "Due diligence & audit technique",
          "Direction de projets complexes multi-équipes",
          "Recrutement et management d'ingénieurs senior",
          "Culture craftsmanship & excellence engineering",
          "Accompagnement grands comptes & scale-ups",
        ],
      },
    ],
    moreLabel: "Secteur public, privé, international",
    moreDesc: "Capacité d'adaptation rapide à tout domaine métier grâce à 20 ans de missions variées.",
  },

  experience: {
    label: "Expérience",
    titlePrefix: "20 ans de ",
    titleHighlight: "terrain",
    subtitle: "Banque, énergie, retail, secteur public : des systèmes critiques cloud-native pour les plus grands.",
    stackLabel: "Stack",
    items: [
      {
        company: "Cartan Trade",
        role: "Senior Tech Lead & Architect",
        period: "Août 2026 – présent",
        emoji: "institution",
        highlights: [
          "Intégration de capacités IA avancées (Claude) pour révolutionner l'évaluation du risque et automatiser les workflows de décision",
          "Traduction de la logique métier du risque de crédit en solutions techniques innovantes, en lien direct avec les équipes business",
          "Co-construction de modèles de calcul de risque de défaut avec les équipes tech en place",
          "Architecture fullstack scalable sur Google Cloud Platform (GCP), développement Kotlin",
        ],
        stack: "Kotlin · Google Cloud Platform · Claude APIs · Risk Modeling",
      },
      {
        company: "Société Générale CIB (SGCIB)",
        role: "Technical Leader Java Spark Azure AI",
        period: "Jan 2024 – Août 2026",
        emoji: "finance",
        highlights: [
          "Architecture cloud-native sur Azure & Kubernetes pour un moteur de risque de contrepartie",
          "Réduction significative (jusqu'à 50%) du temps de traitement via optimisation algorithmique et Spark tuning",
          "Accélération notable (~30%) du cycle de dev grâce à l'intégration de GitHub Copilot et d'outils AI",
          "Culture TDD/BDD et Clean Code : réduction significative des bugs en production",
          "CI/CD automatisé (GitHub/Jenkins) en environnement hautement régulé",
        ],
        stack: "Java · Spring Boot · Apache Spark · Azure · Kubernetes · Kafka · AI · Jenkins",
      },
      {
        company: "WeHighTech",
        role: "CEO & Fondateur",
        period: "Jan 2017 – présent",
        emoji: "rocket",
        highlights: [
          "Création et direction d'une société de conseil tech orientée qualité et excellence",
          "Pilotage de missions freelance pour grands comptes (banque, énergie, retail, justice)",
          "Recrutement et management d'ingénieurs seniors",
          "Culture d'entreprise centrée sur le craftsmanship et l'innovation",
        ],
        stack: "Kotlin · Angular · Java · Spring Boot · Cloud",
      },
      {
        company: "GRTgaz",
        role: "Technical Leader Fullstack Java Angular AWS Terraform",
        period: "Mar 2022 – Fév 2024",
        emoji: "energy",
        highlights: [
          "Conception et développement d'une plateforme de gestion de distribution énergétique",
          "Architecture microservices avec Axon Framework et programmation réactive (Reactor)",
          "CI/CD sur AWS avec Terraform - Infrastructure as Code",
          "Mentoring développeurs, code review, pair programming, TDD",
        ],
        stack: "Java 17 · Kotlin · Spring Boot · Axon · Reactor · Angular · AWS · Terraform · Kafka",
      },
      {
        company: "Groupe Casino",
        role: "Lead Backend Developer Java Kotlin GCP",
        period: "Jan 2021 – Mar 2022",
        emoji: "retail",
        highlights: [
          "Conception et développement d'une plateforme de gestion de campagnes et offres",
          "Design d'API, développement Kotlin & Java, pratiques SOLID, Kiss, DRY",
          "CI/CD sur Google Cloud Platform (GCP) avec Kubernetes",
          "TDD, BDD, functional programming, mentoring",
        ],
        stack: "Java 11 · Kotlin · Spring Boot · GCP · Kubernetes · PostgreSQL · Liquibase",
      },
      {
        company: "Ministère de la Justice",
        role: "Technical Leader Full Stack",
        period: "Jun 2020 – Jan 2021",
        emoji: "justice",
        highlights: [
          "Lead technique full-stack (Java/Kotlin back + Angular front)",
          "BBL internes : Functional Programming with Java Streams, Kotlin from Zero to Hero",
          "Craftsmanship : Clean Code, TDD, code review, pair programming",
          "Déploiement sur Openshift",
        ],
        stack: "Java 11 · Kotlin · Spring Boot · Angular · Jenkins · Docker · Openshift",
      },
    ],
  },

  education: {
    label: "Formation",
    titlePrefix: "Excellence ",
    titleHighlight: "académique",
    subtitle: "Une formation d'ingénieur ancrée dans la technique, élevée par une vision stratégique de haut niveau.",
    projectLabel: "Projet de transformation",
    skillsLabel: "Compétences développées",
    items: [
      {
        school: "École Polytechnique",
        logo: "graduation",
        degree: "Executive MBA",
        field: "Stratège de la Transformation Numérique",
        promo: "Promotion 7",
        year: "2024",
        highlight: true,
        color: "#D4AF37",
        project: "Transformation d'un distributeur de produits de cybersécurité en fournisseur de services managés.",
        skills: [
          "Concevoir et impulser la stratégie de transformation numérique",
          "Créer de la valeur à partir des technologies de pointe",
          "Construire des business models basés sur l'innovation technologique",
          "Déclencher et animer la dynamique collective de transformation",
          "Accompagner les collectifs dans le changement",
        ],
        url: "https://www.polytechnique.edu/executive-education",
      },
      {
        school: "École Polytechnique",
        logo: "graduation",
        degree: "Certification",
        field: "Digital Business - Act on the Digital World",
        promo: "",
        year: "2023",
        highlight: false,
        color: "#D4AF37",
        project: "",
        skills: [],
        url: "https://www.polytechnique.edu/executive-education",
      },
      {
        school: "EMI - École Mohammadia d'Ingénieurs",
        logo: "gear",
        degree: "Diplôme d'Ingénieur",
        field: "Génie Informatique",
        promo: "",
        year: "2004",
        highlight: false,
        color: "#D4AF37",
        project: "",
        skills: [],
        url: "",
      },
    ],
  },

  projects: {
    label: "Projets & Contributions",
    titlePrefix: "La preuve ",
    titleHighlight: "par les actes",
    subtitle: "Code open-source, talks, articles et réflexions sur l'IA, l'architecture et le leadership tech.",
    linkedinInsightsTitle: "Insights LinkedIn",
    followersLabel: "7 735 abonnés",
    reactionsLabel: "réactions",
    githubTitle: "GitHub Open Source",
    reposLabel: "153 repos",
    talksTitle: "Talks & Présentations",
    slideshareLabel: "SlideShare",
    blogTitle: "Articles de blog",
    blogLabel: "riadhmnasri.fr",
    items: [
      {
        title: "kotlin-counterparty-risk",
        desc: "Librairie OSS Kotlin/JVM : exposition, expected loss et CVA sur repos et prêts de titres",
        tags: ["Kotlin", "Finance", "Risk"],
        url: "https://github.com/riadh-mnasri/kotlin-counterparty-risk",
      },
      {
        title: "kotlin-chess-tournament",
        desc: "Librairie OSS Kotlin/JVM : appariement Swiss, calcul Elo et classements de tournoi",
        tags: ["Kotlin", "OSS", "Algorithmes"],
        url: "https://github.com/riadh-mnasri/kotlin-chess-tournament",
      },
      {
        title: "missionmatch",
        desc: "App de référence DDD, Hexagonal, TDD/BDD et Kafka - Kotlin/Spring Boot + Angular, Terraform/AWS",
        tags: ["Kotlin", "DDD", "Kafka"],
        url: "https://github.com/riadh-mnasri/missionmatch",
      },
      {
        title: "hexray",
        desc: "CLI d'audit d'architecture hexagonale/DDD (TypeScript + Kotlin), rapports générés par agent IA",
        tags: ["CLI", "Architecture", "AI"],
        url: "https://github.com/riadh-mnasri/hexray",
      },
    ],
    talks: [
      { title: "Architectures Microservices", views: "871 vues", icon: "architecture" },
      { title: "Git l'essentiel", views: "1 200 vues", icon: "github" },
      { title: "Discover Micronaut", views: "306 vues", icon: "rocket" },
      { title: "Kotlin ArrowKt", views: "318 vues", icon: "target" },
      { title: "BBL Reactive Programming", views: "197 vues", icon: "energy" },
      { title: "Functional Programming with Kotlin", views: "122 vues", icon: "λ" },
    ],
    linkedinPosts: [
      {
        title: "L'IA comme partenaire de réflexion, pas générateur de code",
        excerpt: "Après plus de 20 ans de développement, je ne pensais pas qu'un assistant IA allait encore me faire évoluer dans ma façon de concevoir du code. La qualité des réponses dépend bien plus des questions que je pose que du modèle utilisé.",
        tags: ["AI", "Craftsmanship", "Réflexion"],
        reactions: 25,
      },
      {
        title: "La documentation qui se met à jour toute seule",
        excerpt: "Living Documentation : j'ai testé, et ça change la vie d'une équipe. Nous connaissons tous cette situation où un nouveau développeur se retrouve face à une doc obsolète...",
        tags: ["Claude Code", "Documentation", "Dev Augmenté"],
        reactions: 12,
      },
      {
        title: "Formation Claude Code @ SFEIR Institute",
        excerpt: "Le métier de développeur évolue à vitesse grand V, et la transition vers le paradigme du développeur augmenté est désormais une réalité. Je viens de finaliser la formation Claude Code chez SFEIR Institut.",
        tags: ["Claude Code", "Anthropic", "Dev Augmenté"],
        reactions: 23,
      },
    ],
    blogPosts,
  },

  certifications: {
    label: "Certifications & Communauté",
    titlePrefix: "19 certifications, ",
    titleHighlight: "une expertise prouvée",
    subtitle: "Des certifications reconnues sur les domaines les plus stratégiques : IA, Cloud, Architecture, JVM.",
    aiBadge: "IA & Anthropic - 2026",
    allLabel: "Toutes les certifications",
    communityTitlePrefix: "Engagement ",
    communityTitleHighlight: "communautaire",
    items: certifications,
    community: [
      { icon: "graduation", name: "École Polytechnique", desc: "Executive Master - Promo 7 Stratège du Numérique" },
      { icon: "ai", name: "Anthropic Certified", desc: "Claude Code 101 · Introduction to Subagents" },
      { icon: "jvm", name: "JUG Paris", desc: "Java User Group - Membre actif" },
      { icon: "sandwich", name: "Brown Bag Lunch", desc: "Speaker & formateur (Kotlin, Java, FP...)" },
      { icon: "github", name: "GitHub", desc: "153 repos · Arctic Code Vault Contributor" },
      { icon: "pen", name: "Blog Technique", desc: "riadhmnasri.fr - Architecture, IA, Finance & risque" },
      { icon: "linkedin", name: "LinkedIn", desc: "7 735 abonnés · Veille AI & Architecture" },
      { icon: "chess", name: "Chess Club CEBC", desc: "Bois-Colombes - Accompagnement jeunes joueurs" },
    ],
  },

  testimonials: {
    label: "Témoignages",
    titlePrefix: "Ce que disent ",
    titleHighlight: "mes clients",
    subtitle: "Des résultats concrets, des équipes satisfaites. Quelques retours de collaborateurs et clients.",
    items: [
      {
        quote: "J'ai travaillé avec Riadh en tant que développeur dans l'équipe qu'il dirigeait. C'est un profil qui correspond à toute entreprise cherchant quelqu'un avec une grande capacité de proposition et de résolution de problèmes, avec un time-to-market réduit. Il est doué et n'hésite pas à aider les autres grâce à son immense connaissance en informatique. Ce fut un réel plaisir de travailler avec lui.",
        author: "Abdelaziz Houmadi",
        company: "Senior Full Stack Java & AWS",
        emoji: "developer",
        color: "#D4AF37",
      },
      {
        quote: "J'ai eu la chance de travailler avec Riadh, un collaborateur très corporate. Il a un réel sens de l'engagement pour mener à bien ses projets dans les délais au bénéfice de ses clients. Son expertise technique sur les architectures orientées services, sa capacité à faire progresser chaque membre de sa squad techniquement et humainement, sa facilité à interagir avec les équipes qui gravitent autour de lui font de lui un atout majeur sur un projet.",
        author: "Mounir Bayach",
        company: "Ingénieur d'affaires (ex-manager direct)",
        emoji: "compass",
        color: "#22C55E",
      },
      {
        quote: "J'ai eu le privilège de travailler dans la même équipe que Riadh. Riadh est un développeur passionné, travailleur, avec de solides compétences, et aime partager ses connaissances. Son esprit d'équipe, son professionnalisme et sa recherche de l'excellence sont des qualités que j'ai beaucoup appréciées chez lui.",
        author: "Van-Minh Pho",
        company: "Développeur / Technical Lead Java & Kotlin",
        emoji: "handshake",
        color: "#A78BFA",
      },
      {
        quote: "J'ai eu le plaisir de travailler avec Riadh. C'est un développeur Java et Kotlin solide et passionné, pour qui la qualité et le travail bien fait comptent énormément. C'est aussi un excellent orateur, qui partage ses connaissances lors d'événements tech (Brown Bag Lunch). Si vous cherchez un développeur senior solide, je le recommande chaleureusement.",
        author: "Romain Schlick",
        company: "Technical Leader & Senior Developer",
        emoji: "mic",
        color: "#38BDF8",
      },
    ],
    footerPrefix: "Recommandations réelles, publiées sur mon ",
    footerLinkLabel: "profil LinkedIn",
  },

  services: {
    label: "Services",
    titlePrefix: "Ce que je peux faire ",
    titleHighlight: "pour vous",
    subtitle: "Disponible en mission freelance à Paris et en remote. TJM : 780€/jour.",
    items: [
      {
        icon: "☁️",
        title: "Migration Cloud-Native & Architecture",
        desc: "Migration de systèmes legacy vers le Cloud (AWS, Azure, GCP). Conception d'architectures microservices scalables avec une disponibilité visée de 99%+. Kubernetes, Terraform, Kafka.",
        target: "DSI, CTO, grands comptes & scale-ups",
      },
      {
        icon: "🤖",
        title: "AI Integration & Modernisation",
        desc: "Intégration de l'IA dans vos pipelines de développement (Copilot, Claude, LLM). Sécurisation des architectures (OWASP, OAuth2/OIDC). Accélération du Time-to-Market.",
        target: "Équipes tech souhaitant adopter l'IA",
      },
      {
        icon: "🧭",
        title: "Technical Leadership & Mentoring",
        desc: "Pilotage technique d'équipes, culture craftsmanship (TDD, Clean Code, DDD), DevSecOps. Je fais le pont entre stratégie C-level et réalité ingénierie terrain.",
        target: "Startups, ETI & grands groupes",
      },
    ],
    dayRateBig: "780€ / jour",
    dayRateSubtitle: "Tarif journalier moyen · Paris & Remote · Disponible dès maintenant",
    ctaButton: "Discutons de votre projet",
  },

  contact: {
    label: "Contact",
    titlePrefix: "Parlons de votre ",
    titleHighlight: "projet",
    subtitle: "Une mission, une formation, un audit technique ? Je réponds en moins de 24h.",
    sentTitle: "Message envoyé !",
    sentDesc: "Je vous réponds dans les 24 heures.",
    namePlaceholder: "Prénom / Nom *",
    emailPlaceholder: "Email *",
    companyPlaceholder: "Entreprise (optionnel)",
    typePlaceholder: "Type de mission",
    typeOptions: ["Architecture technique", "Lead Developer / Tech Lead", "Formation / BBL", "Autre"],
    messagePlaceholder: "Décrivez votre besoin... *",
    errorMessage: "Une erreur est survenue. Contactez-moi directement par email.",
    sendingLabel: "Envoi...",
    sendLabel: "Envoyer le message",
    emailLabel: "Email",
    locationLabel: "Localisation",
    locationValue: "Paris, France · Remote OK",
    maltLabel: "Malt",
    maltCta: "Voir mon profil Malt",
    findMeLabel: "Retrouvez-moi sur",
    githubLabel: "GitHub",
    linkedinLabel: "LinkedIn",
    blogLabel: "Blog",
    availableLabel: "Disponible pour missions",
    dayRate: "780€ / jour",
  },

  footer: {
    role: "Senior Software Architect & Lead Developer",
    lastUpdatedLabel: "Dernière mise à jour",
  },

  chat: {
    toggleOpen: "Poser une question",
    toggleClose: "Fermer",
    title: "Assistant du profil",
    subtitle: "Questions sur Riadh MNASRI",
    emptyPrompt: "Posez une question sur les compétences, l'expérience ou la disponibilité de Riadh.",
    suggestions: [
      "Quelles sont ses compétences en IA ?",
      "Est-il disponible pour une mission ?",
      "Quelle est son expérience en finance de marché ?",
    ],
    inputPlaceholder: "Votre question...",
    errorMessage: "Une erreur est survenue. Réessayez ou écrivez directement à riadh.mnasri@gmail.com.",
  },

  links,
};
