export const CONTENT = {
  hero: {
    name: "Riadh MNASRI",
    title: "Senior Tech Lead & Architect",
    subtitle: "AI-Driven Solutions · Cloud Native · Java & Kotlin Expert",
    tagline: "20 ans d'ingénierie. Des architectures cloud-native qui transforment.\nL'IA au service de votre business.",
    badges: [
      "Anthropic Certified",
      "Java Certifié",
      "Kotlin Certifié",
      "Spring Certifié",
      "Executive Master @ Polytechnique",
      "Paris · Freelance · 780€/j",
    ],
    stats: [
      { value: 20, suffix: "+", label: "ans d'expérience" },
      { value: 7735, suffix: "", label: "abonnés LinkedIn" },
      { value: 780, suffix: "€", label: "TJM journalier" },
      { value: 19, suffix: "", label: "certifications" },
    ],
  },

  about: {
    bio: [
      "J'aide les organisations à transformer leur dette technique en actifs scalables et haute performance. Migration Cloud-Native (AWS, Azure, GCP), intégration de l'IA, sécurisation des architectures Microservices : j'assure que la technologie propulse la croissance plutôt que de la freiner.",
      "20 ans d'excellence ingénierie combinés à une vision stratégique (Executive Master @ École Polytechnique). Certifié Kotlin, Java et Spring, pionnier de l'intégration de l'IA (GitHub Copilot, Claude) dans les workflows de développement.",
      "Actuellement Tech Lead & Architect @ Cartan Trade, sur les initiatives IA et la plateforme de risque de crédit assurance. Disponible pour missions freelance à Paris et en remote.",
    ],
    timeline: [
      { year: "2026", event: "Tech Lead & Architect IA @ Cartan Trade" },
      { year: "2026", event: "Claude Code 101 & Subagents - Anthropic Certified" },
      { year: "2024", event: "Executive MBA - Stratège de la Transformation Numérique, École Polytechnique" },
      { year: "2024", event: "Tech Lead Java Spark Azure AI @ Société Générale CIB" },
      { year: "2022", event: "Tech Lead Fullstack Java Angular AWS @ GRTgaz" },
      { year: "2021", event: "Lead Backend Java Kotlin GCP @ Groupe Casino" },
      { year: "2020", event: "Tech Lead Full Stack @ Ministère de la Justice" },
      { year: "2020", event: "Kotlin Certified Developer - JetBrains" },
      { year: "2017", event: "CEO WeHighTech · Spring Certified Professional" },
      { year: "2007", event: "Sun Certified Java Programmer - Oracle" },
      { year: "2004", event: "Diplôme Ingénieur Informatique" },
    ],
  },

  skills: [
    {
      icon: "architecture",
      category: "Architecture",
      items: ["Microservices", "DDD", "Hexagonal", "Event-Driven", "CQRS", "Cloud-Native"],
    },
    {
      icon: "jvm",
      category: "JVM & Langages",
      items: ["Java 21+", "Kotlin", "Scala", "TypeScript", "Spring Boot", "Reactor"],
    },
    {
      icon: "cloud",
      category: "Cloud & Infra",
      items: ["AWS", "Azure", "GCP", "Kubernetes", "Docker", "Terraform"],
    },
    {
      icon: "ai",
      category: "AI & Innovation",
      items: ["GitHub Copilot", "Claude / Anthropic", "AI Agents", "LLM Integration", "Cybersécurité", "OWASP"],
    },
    {
      icon: "data",
      category: "Data & Messaging",
      items: ["Apache Kafka", "Apache Spark", "Elasticsearch", "PostgreSQL", "MongoDB", "Axon"],
    },
    {
      icon: "quality",
      category: "Qualité & Leadership",
      items: ["TDD", "BDD", "Clean Code", "DevSecOps", "CI/CD", "Mentoring"],
    },
  ],

  domains: [
    {
      icon: "finance",
      sector: "Finance de Marché & Risque",
      color: "#C2A46B",
      client: "Société Générale CIB",
      items: [
        "Risque de contrepartie (CCR / XVA)",
        "Moteurs de calcul de risque cloud-native",
        "Régulation financière (FRTB, CRD IV/V)",
        "Capital Markets & CIB",
        "Optimisation de performance Spark (~+50%)",
      ],
    },
    {
      icon: "energy",
      sector: "Énergie & Utilities",
      color: "#38BDF8",
      client: "GRTgaz",
      items: [
        "Gestion de la distribution énergétique",
        "Réseau de transport de gaz national",
        "Opérateurs d'Importance Vitale (OIV)",
        "Systèmes temps réel haute disponibilité",
        "Infrastructure critique & SLA stricts",
      ],
    },
    {
      icon: "retail",
      sector: "Retail & Grande Distribution",
      color: "#22C55E",
      client: "Groupe Casino",
      items: [
        "Gestion de campagnes & offres promotionnelles",
        "Moteurs de fidélisation client",
        "Catalogue produit à grande échelle",
        "Plateformes e-commerce & marketing",
        "Architecture événementielle GCP",
      ],
    },
    {
      icon: "justice",
      sector: "Secteur Public & Justice",
      color: "#64748B",
      client: "Ministère de la Justice",
      items: [
        "Dématérialisation de procédures judiciaires",
        "Sécurité & conformité RGPD / État",
        "Interopérabilité des systèmes d'État",
        "Déploiement Openshift souverain",
        "Accompagnement transformation numérique",
      ],
    },
    {
      icon: "rocket",
      sector: "Conseil & Transformation Digitale",
      color: "#A78BFA",
      client: "WeHighTech (CEO)",
      items: [
        "Due diligence & audit technique",
        "Direction de projets complexes multi-équipes",
        "Recrutement et management d'ingénieurs senior",
        "Culture craftsmanship & excellence engineering",
        "Accompagnement grands comptes & scale-ups",
      ],
    },
  ],

  experience: [
    {
      company: "Cartan Trade",
      role: "Senior Tech Lead & Architect",
      period: "Août 2026 – présent",
      emoji: "institution",
      highlights: [
        "Intégration de capacités IA avancées (Claude) pour révolutionner l'évaluation du risque et automatiser les workflows de décision",
        "Traduction de la logique métier du risque de crédit en solutions techniques innovantes, en lien direct avec les équipes business",
        "Co-construction de modèles de calcul de risque de défaut avec les équipes tech en place",
        "Architecture fullstack scalable sur Google Cloud Platform (GCP), développement Kotlin",
      ],
      stack: "Kotlin · Google Cloud Platform · Claude APIs · Risk Modeling",
    },
    {
      company: "Société Générale CIB (SGCIB)",
      role: "Technical Leader Java Spark Azure AI",
      period: "Jan 2024 – Août 2026",
      emoji: "finance",
      highlights: [
        "Architecture cloud-native sur Azure & Kubernetes pour un moteur de risque de contrepartie",
        "Réduction significative (jusqu'à 50%) du temps de traitement via optimisation algorithmique et Spark tuning",
        "Accélération notable (~30%) du cycle de dev grâce à l'intégration de GitHub Copilot et d'outils AI",
        "Culture TDD/BDD et Clean Code : réduction significative des bugs en production",
        "CI/CD automatisé (GitHub/Jenkins) en environnement hautement régulé",
      ],
      stack: "Java · Spring Boot · Apache Spark · Azure · Kubernetes · Kafka · AI · Jenkins",
    },
    {
      company: "WeHighTech",
      role: "CEO & Fondateur",
      period: "Jan 2017 – présent",
      emoji: "rocket",
      highlights: [
        "Création et direction d'une société de conseil tech orientée qualité et excellence",
        "Pilotage de missions freelance pour grands comptes (banque, énergie, retail, justice)",
        "Recrutement et management d'ingénieurs seniors",
        "Culture d'entreprise centrée sur le craftsmanship et l'innovation",
      ],
      stack: "Kotlin · Angular · Java · Spring Boot · Cloud",
    },
    {
      company: "GRTgaz",
      role: "Technical Leader Fullstack Java Angular AWS Terraform",
      period: "Mar 2022 – Fév 2024",
      emoji: "energy",
      highlights: [
        "Conception et développement d'une plateforme de gestion de distribution énergétique",
        "Architecture microservices avec Axon Framework et programmation réactive (Reactor)",
        "CI/CD sur AWS avec Terraform - Infrastructure as Code",
        "Mentoring développeurs, code review, pair programming, TDD",
      ],
      stack: "Java 17 · Kotlin · Spring Boot · Axon · Reactor · Angular · AWS · Terraform · Kafka",
    },
    {
      company: "Groupe Casino",
      role: "Lead Backend Developer Java Kotlin GCP",
      period: "Jan 2021 – Mar 2022",
      emoji: "retail",
      highlights: [
        "Conception et développement d'une plateforme de gestion de campagnes et offres",
        "Design d'API, développement Kotlin & Java, pratiques SOLID, Kiss, DRY",
        "CI/CD sur Google Cloud Platform (GCP) avec Kubernetes",
        "TDD, BDD, functional programming, mentoring",
      ],
      stack: "Java 11 · Kotlin · Spring Boot · GCP · Kubernetes · PostgreSQL · Liquibase",
    },
    {
      company: "Ministère de la Justice",
      role: "Technical Leader Full Stack",
      period: "Jun 2020 – Jan 2021",
      emoji: "justice",
      highlights: [
        "Lead technique full-stack (Java/Kotlin back + Angular front)",
        "BBL internes : Functional Programming with Java Streams, Kotlin from Zero to Hero",
        "Craftsmanship : Clean Code, TDD, code review, pair programming",
        "Déploiement sur Openshift",
      ],
      stack: "Java 11 · Kotlin · Spring Boot · Angular · Jenkins · Docker · Openshift",
    },
  ],

  projects: [
    {
      title: "kotlin-counterparty-risk",
      desc: "Librairie OSS Kotlin/JVM : exposition, expected loss et CVA sur repos et prêts de titres",
      tags: ["Kotlin", "Finance", "Risk"],
      url: "https://github.com/riadh-mnasri/kotlin-counterparty-risk",
    },
    {
      title: "kotlin-chess-tournament",
      desc: "Librairie OSS Kotlin/JVM : appariement Swiss, calcul Elo et classements de tournoi",
      tags: ["Kotlin", "OSS", "Algorithmes"],
      url: "https://github.com/riadh-mnasri/kotlin-chess-tournament",
    },
    {
      title: "missionmatch",
      desc: "App de référence DDD, Hexagonal, TDD/BDD et Kafka - Kotlin/Spring Boot + Angular, Terraform/AWS",
      tags: ["Kotlin", "DDD", "Kafka"],
      url: "https://github.com/riadh-mnasri/missionmatch",
    },
    {
      title: "hexray",
      desc: "CLI d'audit d'architecture hexagonale/DDD (TypeScript + Kotlin), rapports générés par agent IA",
      tags: ["CLI", "Architecture", "AI"],
      url: "https://github.com/riadh-mnasri/hexray",
    },
  ],

  talks: [
    { title: "Architectures Microservices", views: "871 vues", icon: "architecture" },
    { title: "Git l'essentiel", views: "1 200 vues", icon: "github" },
    { title: "Discover Micronaut", views: "306 vues", icon: "rocket" },
    { title: "Kotlin ArrowKt", views: "318 vues", icon: "target" },
    { title: "BBL Reactive Programming", views: "197 vues", icon: "energy" },
    { title: "Functional Programming with Kotlin", views: "122 vues", icon: "λ" },
  ],

  linkedinPosts: [
    {
      title: "L'IA comme partenaire de réflexion, pas générateur de code",
      excerpt: "Après plus de 20 ans de développement, je ne pensais pas qu'un assistant IA allait encore me faire évoluer dans ma façon de concevoir du code. La qualité des réponses dépend bien plus des questions que je pose que du modèle utilisé.",
      tags: ["AI", "Craftsmanship", "Réflexion"],
      reactions: 25,
    },
    {
      title: "La documentation qui se met à jour toute seule",
      excerpt: "Living Documentation : j'ai testé, et ça change la vie d'une équipe. Nous connaissons tous cette situation où un nouveau développeur se retrouve face à une doc obsolète...",
      tags: ["Claude Code", "Documentation", "Dev Augmenté"],
      reactions: 12,
    },
    {
      title: "Formation Claude Code @ SFEIR Institute",
      excerpt: "Le métier de développeur évolue à vitesse grand V, et la transition vers le paradigme du développeur augmenté est désormais une réalité. Je viens de finaliser la formation Claude Code chez SFEIR Institut.",
      tags: ["Claude Code", "Anthropic", "Dev Augmenté"],
      reactions: 23,
    },
  ],

  blogPosts: [
    {
      title: "Le calcul Elo : l'algorithme derrière un classement qui s'auto-corrige",
      date: "30 septembre 2026",
      tags: ["Algorithmes", "Échecs"],
      url: "https://riadhmnasri.fr/fr/blog/le-calcul-elo-lalgorithme-derriere-un-classement-qui-sauto-corrige",
    },
    {
      title: "Le stress testing bancaire, expliqué à un développeur",
      date: "23 septembre 2026",
      tags: ["Finance & risque"],
      url: "https://riadhmnasri.fr/fr/blog/stress-testing-bancaire-explique-a-un-developpeur",
    },
    {
      title: "Les subagents Claude Code : forker plutôt que déléguer",
      date: "19 septembre 2026",
      tags: ["Claude Code", "IA & développement"],
      url: "https://riadhmnasri.fr/fr/blog/subagents-claude-code-forker-plutot-que-deleguer",
    },
    {
      title: "DDD vs Clean Architecture vs Hexagonale, code à l'appui",
      date: "5 septembre 2026",
      tags: ["Architecture", "JVM (Java/Kotlin)"],
      url: "https://riadhmnasri.fr/fr/blog/ddd-vs-clean-vs-hexagonale-code-a-lappui",
    },
  ],

  certifications: [
    { name: "Claude Code 101", org: "Anthropic", year: "2026", color: "#C2A46B", featured: true },
    { name: "Introduction to Subagents", org: "Anthropic", year: "2026", color: "#C2A46B", featured: true },
    { name: "Introduction to Agent Skills", org: "Anthropic", year: "2026", color: "#C2A46B", featured: true },
    { name: "Découvrir Claude IA d'Anthropic", org: "LinkedIn", year: "2026", color: "#C2A46B", featured: true },
    { name: "Claude Code in Action", org: "Anthropic", year: "2026", color: "#C2A46B", featured: true },
    { name: "Gen AI: Unlock Foundational Concepts", org: "Google Cloud", year: "2025", color: "#4285F4", featured: false },
    { name: "IA : au-delà du chatbot", org: "Google Cloud", year: "2025", color: "#4285F4", featured: false },
    { name: "L'essentiel d'Apache Spark", org: "LinkedIn", year: "2024", color: "#C2A46B", featured: false },
    { name: "Introduction to Generative AI", org: "Google", year: "2023", color: "#4285F4", featured: false },
    { name: "Introducing Semantic Kernel: Building AI Apps", org: "LinkedIn", year: "2023", color: "#0A66C2", featured: false },
    { name: "Se lancer dans le recrutement indépendant", org: "LinkedIn", year: "2023", color: "#0A66C2", featured: false },
    { name: "Découvrir Terraform", org: "LinkedIn", year: "2022", color: "#7B42BC", featured: false },
    { name: "Software Architecture: Domain-Driven Design", org: "LinkedIn", year: "2021", color: "#C2A46B", featured: false },
    { name: "L'essentiel de Google Cloud Platform", org: "LinkedIn", year: "2021", color: "#4285F4", featured: false },
    { name: "Javascript: La formation ULTIME", org: "Udemy", year: "2020", color: "#A435F0", featured: false },
    { name: "Angular par la pratique", org: "Udemy", year: "2020", color: "#A435F0", featured: false },
    { name: "Kotlin for Java Developers", org: "Coursera", year: "2020", color: "#0056D2", featured: false },
    { name: "Spring Certified Professional", org: "VMware / SpringSource", year: "2012", color: "#22C55E", featured: false },
    { name: "Sun Certified Java Programmer", org: "Sun MicroSystems", year: "2007", color: "#EF4444", featured: false },
  ],

  community: [
    { icon: "graduation", name: "École Polytechnique", desc: "Executive Master - Promo 7 Stratège du Numérique" },
    { icon: "ai", name: "Anthropic Certified", desc: "Claude Code 101 · Introduction to Subagents" },
    { icon: "jvm", name: "JUG Paris", desc: "Java User Group - Membre actif" },
    { icon: "sandwich", name: "Brown Bag Lunch", desc: "Speaker & formateur (Kotlin, Java, FP...)" },
    { icon: "github", name: "GitHub", desc: "153 repos · Arctic Code Vault Contributor" },
    { icon: "pen", name: "Blog Technique", desc: "riadhmnasri.fr - Architecture, IA, Finance & risque" },
    { icon: "linkedin", name: "LinkedIn", desc: "7 735 abonnés · Veille AI & Architecture" },
    { icon: "chess", name: "Chess Club CEBC", desc: "Bois-Colombes - Accompagnement jeunes joueurs" },
  ],

  services: [
    {
      icon: "cloud",
      title: "Migration Cloud-Native & Architecture",
      desc: "Migration de systèmes legacy vers le Cloud (AWS, Azure, GCP). Conception d'architectures microservices scalables avec une disponibilité visée de 99%+. Kubernetes, Terraform, Kafka.",
      target: "DSI, CTO, grands comptes & scale-ups",
    },
    {
      icon: "ai",
      title: "AI Integration & Modernisation",
      desc: "Intégration de l'IA dans vos pipelines de développement (Copilot, Claude, LLM). Sécurisation des architectures (OWASP, OAuth2/OIDC). Accélération du Time-to-Market.",
      target: "Équipes tech souhaitant adopter l'IA",
    },
    {
      icon: "leadership",
      title: "Technical Leadership & Mentoring",
      desc: "Pilotage technique d'équipes, culture craftsmanship (TDD, Clean Code, DDD), DevSecOps. Je fais le pont entre stratégie C-level et réalité ingénierie terrain.",
      target: "Startups, ETI & grands groupes",
    },
  ],

  testimonials: [
    {
      quote: "J'ai travaillé avec Riadh en tant que développeur dans l'équipe qu'il dirigeait. C'est un profil qui correspond à toute entreprise cherchant quelqu'un avec une grande capacité de proposition et de résolution de problèmes, avec un time-to-market réduit. Il est doué et n'hésite pas à aider les autres grâce à son immense connaissance en informatique. Ce fut un réel plaisir de travailler avec lui.",
      author: "Abdelaziz Houmadi",
      company: "Senior Full Stack Java & AWS",
      emoji: "developer",
      color: "#C2A46B",
    },
    {
      quote: "J'ai eu la chance de travailler avec Riadh, un collaborateur très corporate. Il a un réel sens de l'engagement pour mener à bien ses projets dans les délais au bénéfice de ses clients. Son expertise technique sur les architectures orientées services, sa capacité à faire progresser chaque membre de sa squad techniquement et humainement, sa facilité à interagir avec les équipes qui gravitent autour de lui font de lui un atout majeur sur un projet.",
      author: "Mounir Bayach",
      company: "Ingénieur d'affaires (ex-manager direct)",
      emoji: "compass",
      color: "#22C55E",
    },
    {
      quote: "J'ai eu le privilège de travailler dans la même équipe que Riadh. Riadh est un développeur passionné, travailleur, avec de solides compétences, et aime partager ses connaissances. Son esprit d'équipe, son professionnalisme et sa recherche de l'excellence sont des qualités que j'ai beaucoup appréciées chez lui.",
      author: "Van-Minh Pho",
      company: "Développeur / Technical Lead Java & Kotlin",
      emoji: "handshake",
      color: "#A78BFA",
    },
    {
      quote: "J'ai eu le plaisir de travailler avec Riadh. C'est un développeur Java et Kotlin solide et passionné, pour qui la qualité et le travail bien fait comptent énormément. C'est aussi un excellent orateur, qui partage ses connaissances lors d'événements tech (Brown Bag Lunch). Si vous cherchez un développeur senior solide, je le recommande chaleureusement.",
      author: "Romain Schlick",
      company: "Technical Leader & Senior Developer",
      emoji: "mic",
      color: "#38BDF8",
    },
  ],

  links: {
    github: "https://github.com/riadh-mnasri",
    linkedin: "https://www.linkedin.com/in/riadhmnasri",
    malt: "https://www.malt.fr/profile/riadhmnasri",
    blog: "https://www.riadhmnasri.fr",
    twitter: "https://x.com/riadhmnasri",
    slideshare: "https://www.slideshare.net/riadhmnasri",
    email: "riadh.mnasri@gmail.com",
  },
};
